-- MySQL Script generated by MySQL Workbench
-- Tue Apr  8 17:54:44 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cs230_u240217
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cs230_u240217
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cs230_u240217` DEFAULT CHARACTER SET utf8mb4 ;
USE `cs230_u240217` ;



-- -----------------------------------------------------
-- Table `cs230_u240217`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cs230_u240217`.`client` (
  `idClient` INT NOT NULL AUTO_INCREMENT,
  `name` TEXT NOT NULL,
  `email` TEXT NOT NULL,
  `phoneNumber` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idClient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cs230_u240217`.`therapist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cs230_u240217`.`therapist` (
  `idTherapist` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `name` TEXT NOT NULL,
  `email` TEXT NOT NULL,
  `location` TEXT NOT NULL,
  `yearsOfPractice` TINYINT NOT NULL,
  `availability` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`idTherapist`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cs230_u240217`.`session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cs230_u240217`.`session` (
  `idSession` INT NOT NULL AUTO_INCREMENT,
  `idClient` INT NOT NULL,
  `idTherapist` INT NOT NULL,
  `date` DATE NOT NULL,
  `length` INT NOT NULL,
  `frequency` ENUM("WEEKLY", "MONTHLY") NOT NULL DEFAULT 'WEEKLY',
  `notes` TEXT NULL,
  INDEX `fk_table1_client1_idx` (`idClient` ASC) VISIBLE,
  INDEX `fk_table1_therapist1_idx` (`idTherapist` ASC) VISIBLE,
  PRIMARY KEY (`idSession`),
  CONSTRAINT `fk_table1_client1`
    FOREIGN KEY (`idClient`)
    REFERENCES `cs230_u240217`.`client` (`idClient`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_table1_therapist1`
    FOREIGN KEY (`idTherapist`)
    REFERENCES `cs230_u240217`.`therapist` (`idTherapist`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
