-- MySQL Script generated by MySQL Workbench
-- Wed Apr  2 11:03:23 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cs230_u240217
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cs230_u240217
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cs230_u240217` DEFAULT CHARACTER SET utf8mb4 ;
USE `cs230_u240217` ;

-- -----------------------------------------------------
-- Table `cs230_u240217`.`albums`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cs230_u240217`.`albums` (
  `idalbum` INT(11) NOT NULL AUTO_INCREMENT,
  `numberListens` INT(11) NOT NULL DEFAULT 0,
  `name` TEXT NOT NULL,
  `releaseYear` YEAR(4) NOT NULL,
  PRIMARY KEY (`idalbum`))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `cs230_u240217`.`artists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cs230_u240217`.`artists` (
  `idartist` INT(11) NOT NULL AUTO_INCREMENT,
  `name` TEXT NOT NULL,
  `monthlyListeners` INT(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idartist`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `cs230_u240217`.`albums_artists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cs230_u240217`.`albums_artists` (
  `idalbum` INT(11) NOT NULL,
  `idartist` INT(11) NOT NULL,
  UNIQUE INDEX `albums_artists_unique` (`idalbum` ASC, `idartist` ASC) VISIBLE,
  INDEX `fk_albums_artists_albums1_idx` (`idalbum` ASC) VISIBLE,
  INDEX `fk_albums_artists_artists1_idx` (`idartist` ASC) VISIBLE,
  CONSTRAINT `fk_albums_artists_albums1`
    FOREIGN KEY (`idalbum`)
    REFERENCES `cs230_u240217`.`albums` (`idalbum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_albums_artists_artists1`
    FOREIGN KEY (`idartist`)
    REFERENCES `cs230_u240217`.`artists` (`idartist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `cs230_u240217`.`songs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cs230_u240217`.`songs` (
  `idsong` INT(11) NOT NULL AUTO_INCREMENT,
  `name` TEXT NOT NULL,
  `releaseYear` YEAR(4) NOT NULL,
  `idArtistWriter` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idsong`),
  INDEX `fk_songs_artists_idx` (`idArtistWriter` ASC) VISIBLE,
  CONSTRAINT `fk_songs_artists`
    FOREIGN KEY (`idArtistWriter`)
    REFERENCES `cs230_u240217`.`artists` (`idartist`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 179
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `cs230_u240217`.`albums_songs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cs230_u240217`.`albums_songs` (
  `idalbum` INT(11) NOT NULL,
  `idsong` INT(11) NOT NULL,
  UNIQUE INDEX `albums_songs_unique` (`idalbum` ASC, `idsong` ASC) VISIBLE,
  INDEX `fk_albums_songs_albums1_idx` (`idalbum` ASC) VISIBLE,
  INDEX `fk_albums_songs_songs1_idx` (`idsong` ASC) VISIBLE,
  CONSTRAINT `fk_albums_songs_albums1`
    FOREIGN KEY (`idalbum`)
    REFERENCES `cs230_u240217`.`albums` (`idalbum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_albums_songs_songs1`
    FOREIGN KEY (`idsong`)
    REFERENCES `cs230_u240217`.`songs` (`idsong`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `cs230_u240217`.`genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cs230_u240217`.`genres` (
  `idgenre` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idgenre`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `cs230_u240217`.`artists_genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cs230_u240217`.`artists_genres` (
  `idgenre` INT(11) NOT NULL,
  `idartist` INT(11) NOT NULL,
  UNIQUE INDEX `artists_genres_unique` (`idgenre` ASC, `idartist` ASC) VISIBLE,
  INDEX `fk_artists_genres_genres1_idx` (`idgenre` ASC) VISIBLE,
  INDEX `fk_artists_genres_artists1_idx` (`idartist` ASC) VISIBLE,
  CONSTRAINT `fk_artists_genres_artists1`
    FOREIGN KEY (`idartist`)
    REFERENCES `cs230_u240217`.`artists` (`idartist`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_artists_genres_genres1`
    FOREIGN KEY (`idgenre`)
    REFERENCES `cs230_u240217`.`genres` (`idgenre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `cs230_u240217`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cs230_u240217`.`client` (
  `idClient` INT NOT NULL AUTO_INCREMENT,
  `name` TEXT NOT NULL,
  `email` TEXT NOT NULL,
  `phoneNumber` VARCHAR(45) NOT NULL,
  `frequency` ENUM("WEEKLY", "MONTHLY") NOT NULL DEFAULT 'MONTHLY',
  PRIMARY KEY (`idClient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cs230_u240217`.`therapist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cs230_u240217`.`therapist` (
  `idTherapist` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `name` TEXT NOT NULL,
  `email` TEXT NOT NULL,
  `location` TEXT NOT NULL,
  `yearsOfPractice` TINYINT NOT NULL,
  `availability` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`idTherapist`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cs230_u240217`.`session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cs230_u240217`.`session` (
  `idSession` INT NOT NULL AUTO_INCREMENT,
  `idClient` INT NOT NULL,
  `idTherapist` INT NOT NULL,
  `date` DATE NOT NULL,
  `length` INT NOT NULL,
  INDEX `fk_table1_client1_idx` (`idClient` ASC) VISIBLE,
  INDEX `fk_table1_therapist1_idx` (`idTherapist` ASC) VISIBLE,
  PRIMARY KEY (`idSession`),
  CONSTRAINT `fk_table1_client1`
    FOREIGN KEY (`idClient`)
    REFERENCES `cs230_u240217`.`client` (`idClient`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_table1_therapist1`
    FOREIGN KEY (`idTherapist`)
    REFERENCES `cs230_u240217`.`therapist` (`idTherapist`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cs230_u240217`.`notes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cs230_u240217`.`notes` (
  `idnotes` INT NOT NULL AUTO_INCREMENT,
  `idSession` INT NOT NULL,
  `note` TEXT NOT NULL,
  PRIMARY KEY (`idnotes`),
  INDEX `fk_notes_session1_idx` (`idSession` ASC) VISIBLE,
  CONSTRAINT `fk_notes_session1`
    FOREIGN KEY (`idSession`)
    REFERENCES `cs230_u240217`.`session` (`idSession`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
